//
//  This file was auto-generated by Macaw tools 0.9.7-SNAPSHOT version built on Fri, 13 Apr 2018 08:12:31 +0530 
//
package io.zolontech.imagemanager.impl;

import java.lang.Override;

public class EmployeeDB implements com.cfx.service.api.Service, io.zolontech.imagemanager.EmployeeDB {
  @Override
  public void initialize(com.cfx.service.api.config.Configuration config) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void start(com.cfx.service.api.StartContext startContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void stop(com.cfx.service.api.StopContext stopContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public String addEmployee(io.zolontech.imagemanager.Employee employee) {
    // TODO: Auto-generated code;
    return null;
  }

  @Override
  public io.zolontech.imagemanager.Employee getEmployeeById(io.zolontech.imagemanager.Employee employeeId) {
    // TODO: Auto-generated code;
    return null;
  }
}
