//
//  This file was auto-generated by Macaw tools 0.9.7-SNAPSHOT version built on Fri, 13 Apr 2018 08:12:31 +0530 
//
package io.zolontech.imagemanager.impl;

import java.lang.Override;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import io.zolontech.imagemanager.Employee;

public class EmployeeDB implements com.cfx.service.api.Service, io.zolontech.imagemanager.EmployeeDB {

  private Map<String, Employee> employees = null;
	
  @Override
  public void initialize(com.cfx.service.api.config.Configuration config) throws com.cfx.service.api.ServiceException {
	  employees = new HashMap<>();
  }

  @Override
  public void start(com.cfx.service.api.StartContext startContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void stop(com.cfx.service.api.StopContext stopContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public String addEmployee(io.zolontech.imagemanager.Employee employee) {
	  if (employee.getEmployeeId() == null) {
		  employee.setEmailId(UUID.randomUUID().toString());
		  employees.put(employee.getEmployeeId(), employee);
	  }
	  else {
		  throw new RuntimeException("Employee already exists with the specified Employee ID: " + employee.getEmployeeId());
	  }
	  return employee.getEmployeeId();
  }

  @Override
  public io.zolontech.imagemanager.Employee getEmployeeById(String employeeId) {
	  Employee employee = employees.get(employeeId);
	  if (employee == null) {
		  throw new RuntimeException("Employee does not exist with the specified Employee ID: " + employeeId);
	  }
    return employee;
  }

	@Override
	public String welcome() {
		return "Welcome!";
	}
}
